# Generated by debtap
# Maintainer: gg
# Contributor: gg
pkgname=kalipi-kernel
pkgver=4.19.15
pkgrel=1
pkgdesc="This package contains the Kali-Pi Linux kernel."
arch=('armv6h')
url="https://re4son-kernel.com"
license=('g')
groups=('')
provides=('linux')
replaces=('raspberrypi-kernel')
backup=('etc/default/kalipi-kernel')
options=('!strip' '!emptydirs')
install=${pkgname}.install
source=("https://github.com/3xitLight/RPi/blob/master/kalipi-kernel_4.19.15-20190123_armhf.deb?raw=true")
sha512sums=('dbe0258b0224983e132f2686139b63e4f1d44be99d078508706a9cae8dbf4f7e9cb01fd4af851fda457cca3f6011d611141b1f32423fed1596bb429d4fd92c90')

package(){

	# Extract package data
	tar xf data.tar.xz -C "${pkgdir}"

	# Fix directories structure differencies
	cd "${pkgdir}"

	install -D -m644 "/usr/share/doc/kalipi-kernel/copyright" "${pkgdir}/usr/share/licenses/${pkgname}/LICENSE"
	mkdir -p usr/lib 2> /dev/null; mv lib/* usr/lib; rm -rf lib

	cd ..

}
